POST http://localhost:8080/users/page
Content-Type: application/json

{
  "example": {
  }
}

####
POST http://localhost:8080/users/page?attributePaths=friends, posts
Content-Type: application/json

{
  "example": {
  }
}

####

POST http://localhost:8080/users/page?attributePaths=person, person.account, person.account.person, person.account.person.account
Content-Type: application/json

{
  "example": {
  }
}